/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * CashierJournalsApi - axios parameter creator
 * @export
 */
export const CashierJournalsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [officeId] 
         * @param {number} [tellerId] 
         * @param {number} [cashierId] 
         * @param {string} [dateRange] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJournalData1: async (officeId?: number, tellerId?: number, cashierId?: number, dateRange?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/cashiersjournal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (officeId !== undefined) {
                localVarQueryParameter['officeId'] = officeId;
            }

            if (tellerId !== undefined) {
                localVarQueryParameter['tellerId'] = tellerId;
            }

            if (cashierId !== undefined) {
                localVarQueryParameter['cashierId'] = cashierId;
            }

            if (dateRange !== undefined) {
                localVarQueryParameter['dateRange'] = dateRange;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CashierJournalsApi - functional programming interface
 * @export
 */
export const CashierJournalsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CashierJournalsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [officeId] 
         * @param {number} [tellerId] 
         * @param {number} [cashierId] 
         * @param {string} [dateRange] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJournalData1(officeId?: number, tellerId?: number, cashierId?: number, dateRange?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJournalData1(officeId, tellerId, cashierId, dateRange, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CashierJournalsApi - factory interface
 * @export
 */
export const CashierJournalsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CashierJournalsApiFp(configuration)
    return {
        /**
         * 
         * @param {number} [officeId] 
         * @param {number} [tellerId] 
         * @param {number} [cashierId] 
         * @param {string} [dateRange] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJournalData1(officeId?: number, tellerId?: number, cashierId?: number, dateRange?: string, options?: any): AxiosPromise<string> {
            return localVarFp.getJournalData1(officeId, tellerId, cashierId, dateRange, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CashierJournalsApi - object-oriented interface
 * @export
 * @class CashierJournalsApi
 * @extends {BaseAPI}
 */
export class CashierJournalsApi extends BaseAPI {
    /**
     * 
     * @param {number} [officeId] 
     * @param {number} [tellerId] 
     * @param {number} [cashierId] 
     * @param {string} [dateRange] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CashierJournalsApi
     */
    public getJournalData1(officeId?: number, tellerId?: number, cashierId?: number, dateRange?: string, options?: any) {
        return CashierJournalsApiFp(this.configuration).getJournalData1(officeId, tellerId, cashierId, dateRange, options).then((request) => request(this.axios, this.basePath));
    }
}
