/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PostCollectionSheetRequest } from '../models';
// @ts-ignore
import { PostCollectionSheetResponse } from '../models';
/**
 * CollectionSheetApi - axios parameter creator
 * @export
 */
export const CollectionSheetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate Individual Collection Sheet:  This Api retrieves repayment details of all individual loans under a office as on a specified meeting date.  Save Collection Sheet:  This Api allows the loan officer to perform bulk repayments of individual loans and deposit of mandatory savings on a given meeting date.
         * @summary Generate Individual Collection Sheet | Save Collection Sheet
         * @param {PostCollectionSheetRequest} postCollectionSheetRequest 
         * @param {string} [command] command
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateCollectionSheet: async (postCollectionSheetRequest: PostCollectionSheetRequest, command?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'postCollectionSheetRequest' is not null or undefined
            assertParamExists('generateCollectionSheet', 'postCollectionSheetRequest', postCollectionSheetRequest)
            const localVarPath = `/collectionsheet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (command !== undefined) {
                localVarQueryParameter['command'] = command;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postCollectionSheetRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CollectionSheetApi - functional programming interface
 * @export
 */
export const CollectionSheetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CollectionSheetApiAxiosParamCreator(configuration)
    return {
        /**
         * Generate Individual Collection Sheet:  This Api retrieves repayment details of all individual loans under a office as on a specified meeting date.  Save Collection Sheet:  This Api allows the loan officer to perform bulk repayments of individual loans and deposit of mandatory savings on a given meeting date.
         * @summary Generate Individual Collection Sheet | Save Collection Sheet
         * @param {PostCollectionSheetRequest} postCollectionSheetRequest 
         * @param {string} [command] command
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateCollectionSheet(postCollectionSheetRequest: PostCollectionSheetRequest, command?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostCollectionSheetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateCollectionSheet(postCollectionSheetRequest, command, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CollectionSheetApi - factory interface
 * @export
 */
export const CollectionSheetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CollectionSheetApiFp(configuration)
    return {
        /**
         * Generate Individual Collection Sheet:  This Api retrieves repayment details of all individual loans under a office as on a specified meeting date.  Save Collection Sheet:  This Api allows the loan officer to perform bulk repayments of individual loans and deposit of mandatory savings on a given meeting date.
         * @summary Generate Individual Collection Sheet | Save Collection Sheet
         * @param {PostCollectionSheetRequest} postCollectionSheetRequest 
         * @param {string} [command] command
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateCollectionSheet(postCollectionSheetRequest: PostCollectionSheetRequest, command?: string, options?: any): AxiosPromise<PostCollectionSheetResponse> {
            return localVarFp.generateCollectionSheet(postCollectionSheetRequest, command, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CollectionSheetApi - object-oriented interface
 * @export
 * @class CollectionSheetApi
 * @extends {BaseAPI}
 */
export class CollectionSheetApi extends BaseAPI {
    /**
     * Generate Individual Collection Sheet:  This Api retrieves repayment details of all individual loans under a office as on a specified meeting date.  Save Collection Sheet:  This Api allows the loan officer to perform bulk repayments of individual loans and deposit of mandatory savings on a given meeting date.
     * @summary Generate Individual Collection Sheet | Save Collection Sheet
     * @param {PostCollectionSheetRequest} postCollectionSheetRequest 
     * @param {string} [command] command
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CollectionSheetApi
     */
    public generateCollectionSheet(postCollectionSheetRequest: PostCollectionSheetRequest, command?: string, options?: any) {
        return CollectionSheetApiFp(this.configuration).generateCollectionSheet(postCollectionSheetRequest, command, options).then((request) => request(this.axios, this.basePath));
    }
}
