/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * DepositAccountOnHoldFundTransactionsApi - axios parameter creator
 * @export
 */
export const DepositAccountOnHoldFundTransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} savingsId 
         * @param {number} [guarantorFundingId] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string} [orderBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAll28: async (savingsId: number, guarantorFundingId?: number, offset?: number, limit?: number, orderBy?: string, sortOrder?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'savingsId' is not null or undefined
            assertParamExists('retrieveAll28', 'savingsId', savingsId)
            const localVarPath = `/savingsaccounts/{savingsId}/onholdtransactions`
                .replace(`{${"savingsId"}}`, encodeURIComponent(String(savingsId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (guarantorFundingId !== undefined) {
                localVarQueryParameter['guarantorFundingId'] = guarantorFundingId;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sortOrder'] = sortOrder;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DepositAccountOnHoldFundTransactionsApi - functional programming interface
 * @export
 */
export const DepositAccountOnHoldFundTransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DepositAccountOnHoldFundTransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} savingsId 
         * @param {number} [guarantorFundingId] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string} [orderBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveAll28(savingsId: number, guarantorFundingId?: number, offset?: number, limit?: number, orderBy?: string, sortOrder?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveAll28(savingsId, guarantorFundingId, offset, limit, orderBy, sortOrder, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DepositAccountOnHoldFundTransactionsApi - factory interface
 * @export
 */
export const DepositAccountOnHoldFundTransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DepositAccountOnHoldFundTransactionsApiFp(configuration)
    return {
        /**
         * 
         * @param {number} savingsId 
         * @param {number} [guarantorFundingId] 
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {string} [orderBy] 
         * @param {string} [sortOrder] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAll28(savingsId: number, guarantorFundingId?: number, offset?: number, limit?: number, orderBy?: string, sortOrder?: string, options?: any): AxiosPromise<string> {
            return localVarFp.retrieveAll28(savingsId, guarantorFundingId, offset, limit, orderBy, sortOrder, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DepositAccountOnHoldFundTransactionsApi - object-oriented interface
 * @export
 * @class DepositAccountOnHoldFundTransactionsApi
 * @extends {BaseAPI}
 */
export class DepositAccountOnHoldFundTransactionsApi extends BaseAPI {
    /**
     * 
     * @param {number} savingsId 
     * @param {number} [guarantorFundingId] 
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {string} [orderBy] 
     * @param {string} [sortOrder] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepositAccountOnHoldFundTransactionsApi
     */
    public retrieveAll28(savingsId: number, guarantorFundingId?: number, offset?: number, limit?: number, orderBy?: string, sortOrder?: string, options?: any) {
        return DepositAccountOnHoldFundTransactionsApiFp(this.configuration).retrieveAll28(savingsId, guarantorFundingId, offset, limit, orderBy, sortOrder, options).then((request) => request(this.axios, this.basePath));
    }
}
