/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetGlobalConfigurationsResponse } from '../models';
// @ts-ignore
import { PutGlobalConfigurationsRequest } from '../models';
// @ts-ignore
import { PutGlobalConfigurationsResponse } from '../models';
/**
 * GlobalConfigurationApi - axios parameter creator
 * @export
 */
export const GlobalConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the list global enable/disable configurations.  Example Requests:  configurations   Returns the list global enable/disable survey configurations.  Example Requests:  configurations/survey
         * @summary Retrieve Global Configuration | Retrieve Global Configuration for surveys
         * @param {boolean} [survey] survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveConfiguration: async (survey?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/configurations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (survey !== undefined) {
                localVarQueryParameter['survey'] = survey;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a global enable/disable configurations.  Example Requests:  configurations/1
         * @summary Retrieve Global Configuration
         * @param {number} configId configId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveOne3: async (configId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'configId' is not null or undefined
            assertParamExists('retrieveOne3', 'configId', configId)
            const localVarPath = `/configurations/{configId}`
                .replace(`{${"configId"}}`, encodeURIComponent(String(configId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an enable/disable global configuration item.
         * @summary Update Global Configuration
         * @param {number} configId configId
         * @param {PutGlobalConfigurationsRequest} putGlobalConfigurationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateConfiguration1: async (configId: number, putGlobalConfigurationsRequest: PutGlobalConfigurationsRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'configId' is not null or undefined
            assertParamExists('updateConfiguration1', 'configId', configId)
            // verify required parameter 'putGlobalConfigurationsRequest' is not null or undefined
            assertParamExists('updateConfiguration1', 'putGlobalConfigurationsRequest', putGlobalConfigurationsRequest)
            const localVarPath = `/configurations/{configId}`
                .replace(`{${"configId"}}`, encodeURIComponent(String(configId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putGlobalConfigurationsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GlobalConfigurationApi - functional programming interface
 * @export
 */
export const GlobalConfigurationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GlobalConfigurationApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the list global enable/disable configurations.  Example Requests:  configurations   Returns the list global enable/disable survey configurations.  Example Requests:  configurations/survey
         * @summary Retrieve Global Configuration | Retrieve Global Configuration for surveys
         * @param {boolean} [survey] survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveConfiguration(survey?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetGlobalConfigurationsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveConfiguration(survey, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a global enable/disable configurations.  Example Requests:  configurations/1
         * @summary Retrieve Global Configuration
         * @param {number} configId configId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveOne3(configId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetGlobalConfigurationsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveOne3(configId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates an enable/disable global configuration item.
         * @summary Update Global Configuration
         * @param {number} configId configId
         * @param {PutGlobalConfigurationsRequest} putGlobalConfigurationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateConfiguration1(configId: number, putGlobalConfigurationsRequest: PutGlobalConfigurationsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutGlobalConfigurationsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateConfiguration1(configId, putGlobalConfigurationsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GlobalConfigurationApi - factory interface
 * @export
 */
export const GlobalConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GlobalConfigurationApiFp(configuration)
    return {
        /**
         * Returns the list global enable/disable configurations.  Example Requests:  configurations   Returns the list global enable/disable survey configurations.  Example Requests:  configurations/survey
         * @summary Retrieve Global Configuration | Retrieve Global Configuration for surveys
         * @param {boolean} [survey] survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveConfiguration(survey?: boolean, options?: any): AxiosPromise<Array<GetGlobalConfigurationsResponse>> {
            return localVarFp.retrieveConfiguration(survey, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a global enable/disable configurations.  Example Requests:  configurations/1
         * @summary Retrieve Global Configuration
         * @param {number} configId configId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveOne3(configId: number, options?: any): AxiosPromise<GetGlobalConfigurationsResponse> {
            return localVarFp.retrieveOne3(configId, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an enable/disable global configuration item.
         * @summary Update Global Configuration
         * @param {number} configId configId
         * @param {PutGlobalConfigurationsRequest} putGlobalConfigurationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateConfiguration1(configId: number, putGlobalConfigurationsRequest: PutGlobalConfigurationsRequest, options?: any): AxiosPromise<PutGlobalConfigurationsResponse> {
            return localVarFp.updateConfiguration1(configId, putGlobalConfigurationsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GlobalConfigurationApi - object-oriented interface
 * @export
 * @class GlobalConfigurationApi
 * @extends {BaseAPI}
 */
export class GlobalConfigurationApi extends BaseAPI {
    /**
     * Returns the list global enable/disable configurations.  Example Requests:  configurations   Returns the list global enable/disable survey configurations.  Example Requests:  configurations/survey
     * @summary Retrieve Global Configuration | Retrieve Global Configuration for surveys
     * @param {boolean} [survey] survey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GlobalConfigurationApi
     */
    public retrieveConfiguration(survey?: boolean, options?: any) {
        return GlobalConfigurationApiFp(this.configuration).retrieveConfiguration(survey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a global enable/disable configurations.  Example Requests:  configurations/1
     * @summary Retrieve Global Configuration
     * @param {number} configId configId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GlobalConfigurationApi
     */
    public retrieveOne3(configId: number, options?: any) {
        return GlobalConfigurationApiFp(this.configuration).retrieveOne3(configId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates an enable/disable global configuration item.
     * @summary Update Global Configuration
     * @param {number} configId configId
     * @param {PutGlobalConfigurationsRequest} putGlobalConfigurationsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GlobalConfigurationApi
     */
    public updateConfiguration1(configId: number, putGlobalConfigurationsRequest: PutGlobalConfigurationsRequest, options?: any) {
        return GlobalConfigurationApiFp(this.configuration).updateConfiguration1(configId, putGlobalConfigurationsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
