/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetSearchResponse } from '../models';
// @ts-ignore
import { PostAdhocQuerySearchRequest } from '../models';
// @ts-ignore
import { PostAdhocQuerySearchResponse } from '../models';
/**
 * SearchAPIApi - axios parameter creator
 * @export
 */
export const SearchAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * AdHocQuery search has more search options, it is a POST request, it uses request body to send search parameters   Mandatory fields:entities  Optional fields:loanStatus, loanProducts, offices, loanDateOption, loanFromDate, loanToDate,  includeOutStandingAmountPercentage, outStandingAmountPercentageCondition,  minOutStandingAmountPercentage and maxOutStandingAmountPercentage OR outStandingAmountPercentage,  includeOutstandingAmount, outstandingAmountCondition,  minOutstandingAmount and maxOutstandingAmount OR outstandingAmount
         * @summary Adhoc query search
         * @param {PostAdhocQuerySearchRequest} postAdhocQuerySearchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        advancedSearch: async (postAdhocQuerySearchRequest: PostAdhocQuerySearchRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'postAdhocQuerySearchRequest' is not null or undefined
            assertParamExists('advancedSearch', 'postAdhocQuerySearchRequest', postAdhocQuerySearchRequest)
            const localVarPath = `/search/advance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postAdhocQuerySearchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Mandatory Fields  search?query=000000001 
         * @summary Retrive Adhoc Search query template
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAdHocSearchQueryTemplate: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/search/template`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Example Requests:  search?query=000000001   search?query=Petra&resource=clients,groups   search?query=Petra&resource=clients,groups&exactMatch=true
         * @summary Search Resources
         * @param {string} [query] query
         * @param {string} [resource] resource
         * @param {boolean} [exactMatch] exactMatch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchData: async (query?: string, resource?: string, exactMatch?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (resource !== undefined) {
                localVarQueryParameter['resource'] = resource;
            }

            if (exactMatch !== undefined) {
                localVarQueryParameter['exactMatch'] = exactMatch;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchAPIApi - functional programming interface
 * @export
 */
export const SearchAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * AdHocQuery search has more search options, it is a POST request, it uses request body to send search parameters   Mandatory fields:entities  Optional fields:loanStatus, loanProducts, offices, loanDateOption, loanFromDate, loanToDate,  includeOutStandingAmountPercentage, outStandingAmountPercentageCondition,  minOutStandingAmountPercentage and maxOutStandingAmountPercentage OR outStandingAmountPercentage,  includeOutstandingAmount, outstandingAmountCondition,  minOutstandingAmount and maxOutstandingAmount OR outstandingAmount
         * @summary Adhoc query search
         * @param {PostAdhocQuerySearchRequest} postAdhocQuerySearchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async advancedSearch(postAdhocQuerySearchRequest: PostAdhocQuerySearchRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostAdhocQuerySearchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.advancedSearch(postAdhocQuerySearchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Mandatory Fields  search?query=000000001 
         * @summary Retrive Adhoc Search query template
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveAdHocSearchQueryTemplate(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSearchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveAdHocSearchQueryTemplate(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Example Requests:  search?query=000000001   search?query=Petra&resource=clients,groups   search?query=Petra&resource=clients,groups&exactMatch=true
         * @summary Search Resources
         * @param {string} [query] query
         * @param {string} [resource] resource
         * @param {boolean} [exactMatch] exactMatch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchData(query?: string, resource?: string, exactMatch?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSearchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchData(query, resource, exactMatch, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SearchAPIApi - factory interface
 * @export
 */
export const SearchAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchAPIApiFp(configuration)
    return {
        /**
         * AdHocQuery search has more search options, it is a POST request, it uses request body to send search parameters   Mandatory fields:entities  Optional fields:loanStatus, loanProducts, offices, loanDateOption, loanFromDate, loanToDate,  includeOutStandingAmountPercentage, outStandingAmountPercentageCondition,  minOutStandingAmountPercentage and maxOutStandingAmountPercentage OR outStandingAmountPercentage,  includeOutstandingAmount, outstandingAmountCondition,  minOutstandingAmount and maxOutstandingAmount OR outstandingAmount
         * @summary Adhoc query search
         * @param {PostAdhocQuerySearchRequest} postAdhocQuerySearchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        advancedSearch(postAdhocQuerySearchRequest: PostAdhocQuerySearchRequest, options?: any): AxiosPromise<PostAdhocQuerySearchResponse> {
            return localVarFp.advancedSearch(postAdhocQuerySearchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Mandatory Fields  search?query=000000001 
         * @summary Retrive Adhoc Search query template
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAdHocSearchQueryTemplate(options?: any): AxiosPromise<GetSearchResponse> {
            return localVarFp.retrieveAdHocSearchQueryTemplate(options).then((request) => request(axios, basePath));
        },
        /**
         * Example Requests:  search?query=000000001   search?query=Petra&resource=clients,groups   search?query=Petra&resource=clients,groups&exactMatch=true
         * @summary Search Resources
         * @param {string} [query] query
         * @param {string} [resource] resource
         * @param {boolean} [exactMatch] exactMatch
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchData(query?: string, resource?: string, exactMatch?: boolean, options?: any): AxiosPromise<GetSearchResponse> {
            return localVarFp.searchData(query, resource, exactMatch, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchAPIApi - object-oriented interface
 * @export
 * @class SearchAPIApi
 * @extends {BaseAPI}
 */
export class SearchAPIApi extends BaseAPI {
    /**
     * AdHocQuery search has more search options, it is a POST request, it uses request body to send search parameters   Mandatory fields:entities  Optional fields:loanStatus, loanProducts, offices, loanDateOption, loanFromDate, loanToDate,  includeOutStandingAmountPercentage, outStandingAmountPercentageCondition,  minOutStandingAmountPercentage and maxOutStandingAmountPercentage OR outStandingAmountPercentage,  includeOutstandingAmount, outstandingAmountCondition,  minOutstandingAmount and maxOutstandingAmount OR outstandingAmount
     * @summary Adhoc query search
     * @param {PostAdhocQuerySearchRequest} postAdhocQuerySearchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchAPIApi
     */
    public advancedSearch(postAdhocQuerySearchRequest: PostAdhocQuerySearchRequest, options?: any) {
        return SearchAPIApiFp(this.configuration).advancedSearch(postAdhocQuerySearchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Mandatory Fields  search?query=000000001 
     * @summary Retrive Adhoc Search query template
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchAPIApi
     */
    public retrieveAdHocSearchQueryTemplate(options?: any) {
        return SearchAPIApiFp(this.configuration).retrieveAdHocSearchQueryTemplate(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Example Requests:  search?query=000000001   search?query=Petra&resource=clients,groups   search?query=Petra&resource=clients,groups&exactMatch=true
     * @summary Search Resources
     * @param {string} [query] query
     * @param {string} [resource] resource
     * @param {boolean} [exactMatch] exactMatch
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchAPIApi
     */
    public searchData(query?: string, resource?: string, exactMatch?: boolean, options?: any) {
        return SearchAPIApiFp(this.configuration).searchData(query, resource, exactMatch, options).then((request) => request(this.axios, this.basePath));
    }
}
