/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SurveyData } from '../models';
/**
 * SpmSurveysApi - axios parameter creator
 * @export
 */
export const SpmSurveysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deactivate Survey
         * @param {number} id 
         * @param {string} [command] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateOrDeactivateSurvey: async (id: number, command?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activateOrDeactivateSurvey', 'id', id)
            const localVarPath = `/surveys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (command !== undefined) {
                localVarQueryParameter['command'] = command;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds a new survey to collect client related data.  Mandatory Fields  countryCode, key, name, questions, responses, sequenceNo, text, description
         * @summary Create a Survey
         * @param {SurveyData} [surveyData] Create survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSurvey: async (surveyData?: SurveyData, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/surveys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(surveyData, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {SurveyData} [surveyData] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSurvey: async (id: number, surveyData?: SurveyData, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('editSurvey', 'id', id)
            const localVarPath = `/surveys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(surveyData, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all Surveys
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAllSurveys1: async (isActive?: boolean, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/surveys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)

            if (isActive !== undefined) {
                localVarQueryParameter['isActive'] = isActive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a Survey
         * @param {number} id Enter id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSurvey: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('findSurvey', 'id', id)
            const localVarPath = `/surveys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpmSurveysApi - functional programming interface
 * @export
 */
export const SpmSurveysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpmSurveysApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deactivate Survey
         * @param {number} id 
         * @param {string} [command] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activateOrDeactivateSurvey(id: number, command?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activateOrDeactivateSurvey(id, command, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Adds a new survey to collect client related data.  Mandatory Fields  countryCode, key, name, questions, responses, sequenceNo, text, description
         * @summary Create a Survey
         * @param {SurveyData} [surveyData] Create survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSurvey(surveyData?: SurveyData, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSurvey(surveyData, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {SurveyData} [surveyData] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editSurvey(id: number, surveyData?: SurveyData, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editSurvey(id, surveyData, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary List all Surveys
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchAllSurveys1(isActive?: boolean, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SurveyData>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchAllSurveys1(isActive, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Retrieve a Survey
         * @param {number} id Enter id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSurvey(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SurveyData>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findSurvey(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SpmSurveysApi - factory interface
 * @export
 */
export const SpmSurveysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpmSurveysApiFp(configuration)
    return {
        /**
         * 
         * @summary Deactivate Survey
         * @param {number} id 
         * @param {string} [command] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateOrDeactivateSurvey(id: number, command?: string, options?: any): AxiosPromise<void> {
            return localVarFp.activateOrDeactivateSurvey(id, command, options).then((request) => request(axios, basePath));
        },
        /**
         * Adds a new survey to collect client related data.  Mandatory Fields  countryCode, key, name, questions, responses, sequenceNo, text, description
         * @summary Create a Survey
         * @param {SurveyData} [surveyData] Create survey
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSurvey(surveyData?: SurveyData, options?: any): AxiosPromise<void> {
            return localVarFp.createSurvey(surveyData, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {SurveyData} [surveyData] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editSurvey(id: number, surveyData?: SurveyData, options?: any): AxiosPromise<string> {
            return localVarFp.editSurvey(id, surveyData, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all Surveys
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchAllSurveys1(isActive?: boolean, options?: any): AxiosPromise<Array<SurveyData>> {
            return localVarFp.fetchAllSurveys1(isActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a Survey
         * @param {number} id Enter id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSurvey(id: number, options?: any): AxiosPromise<SurveyData> {
            return localVarFp.findSurvey(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpmSurveysApi - object-oriented interface
 * @export
 * @class SpmSurveysApi
 * @extends {BaseAPI}
 */
export class SpmSurveysApi extends BaseAPI {
    /**
     * 
     * @summary Deactivate Survey
     * @param {number} id 
     * @param {string} [command] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpmSurveysApi
     */
    public activateOrDeactivateSurvey(id: number, command?: string, options?: any) {
        return SpmSurveysApiFp(this.configuration).activateOrDeactivateSurvey(id, command, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds a new survey to collect client related data.  Mandatory Fields  countryCode, key, name, questions, responses, sequenceNo, text, description
     * @summary Create a Survey
     * @param {SurveyData} [surveyData] Create survey
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpmSurveysApi
     */
    public createSurvey(surveyData?: SurveyData, options?: any) {
        return SpmSurveysApiFp(this.configuration).createSurvey(surveyData, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {SurveyData} [surveyData] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpmSurveysApi
     */
    public editSurvey(id: number, surveyData?: SurveyData, options?: any) {
        return SpmSurveysApiFp(this.configuration).editSurvey(id, surveyData, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all Surveys
     * @param {boolean} [isActive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpmSurveysApi
     */
    public fetchAllSurveys1(isActive?: boolean, options?: any) {
        return SpmSurveysApiFp(this.configuration).fetchAllSurveys1(isActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a Survey
     * @param {number} id Enter id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpmSurveysApi
     */
    public findSurvey(id: number, options?: any) {
        return SpmSurveysApiFp(this.configuration).findSurvey(id, options).then((request) => request(this.axios, this.basePath));
    }
}
