/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetTaxesComponentsResponse } from '../models';
// @ts-ignore
import { PostTaxesComponentsRequest } from '../models';
// @ts-ignore
import { PostTaxesComponentsResponse } from '../models';
// @ts-ignore
import { PutTaxesComponentsTaxComponentIdRequest } from '../models';
// @ts-ignore
import { PutTaxesComponentsTaxComponentIdResponse } from '../models';
/**
 * TaxComponentsApi - axios parameter creator
 * @export
 */
export const TaxComponentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new Tax Component  Mandatory Fields: name, percentage  Optional Fields: debitAccountType, debitAcountId, creditAccountType, creditAcountId, startDate
         * @summary Create a new Tax Component
         * @param {PostTaxesComponentsRequest} postTaxesComponentsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaxCompoent: async (postTaxesComponentsRequest: PostTaxesComponentsRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'postTaxesComponentsRequest' is not null or undefined
            assertParamExists('createTaxCompoent', 'postTaxesComponentsRequest', postTaxesComponentsRequest)
            const localVarPath = `/taxes/component`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postTaxesComponentsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List Tax Components
         * @summary List Tax Components
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAllTaxComponents: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxes/component`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve Tax Component
         * @summary Retrieve Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTaxComponent: async (taxComponentId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'taxComponentId' is not null or undefined
            assertParamExists('retrieveTaxComponent', 'taxComponentId', taxComponentId)
            const localVarPath = `/taxes/component/{taxComponentId}`
                .replace(`{${"taxComponentId"}}`, encodeURIComponent(String(taxComponentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTemplate20: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxes/component/template`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates Tax component. Debit and credit account details cannot be modified. All the future tax components would be replaced with the new percentage.
         * @summary Update Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {PutTaxesComponentsTaxComponentIdRequest} putTaxesComponentsTaxComponentIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaxCompoent: async (taxComponentId: number, putTaxesComponentsTaxComponentIdRequest: PutTaxesComponentsTaxComponentIdRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'taxComponentId' is not null or undefined
            assertParamExists('updateTaxCompoent', 'taxComponentId', taxComponentId)
            // verify required parameter 'putTaxesComponentsTaxComponentIdRequest' is not null or undefined
            assertParamExists('updateTaxCompoent', 'putTaxesComponentsTaxComponentIdRequest', putTaxesComponentsTaxComponentIdRequest)
            const localVarPath = `/taxes/component/{taxComponentId}`
                .replace(`{${"taxComponentId"}}`, encodeURIComponent(String(taxComponentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putTaxesComponentsTaxComponentIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaxComponentsApi - functional programming interface
 * @export
 */
export const TaxComponentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaxComponentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new Tax Component  Mandatory Fields: name, percentage  Optional Fields: debitAccountType, debitAcountId, creditAccountType, creditAcountId, startDate
         * @summary Create a new Tax Component
         * @param {PostTaxesComponentsRequest} postTaxesComponentsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTaxCompoent(postTaxesComponentsRequest: PostTaxesComponentsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostTaxesComponentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTaxCompoent(postTaxesComponentsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List Tax Components
         * @summary List Tax Components
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveAllTaxComponents(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetTaxesComponentsResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveAllTaxComponents(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve Tax Component
         * @summary Retrieve Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveTaxComponent(taxComponentId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTaxesComponentsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveTaxComponent(taxComponentId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveTemplate20(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveTemplate20(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates Tax component. Debit and credit account details cannot be modified. All the future tax components would be replaced with the new percentage.
         * @summary Update Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {PutTaxesComponentsTaxComponentIdRequest} putTaxesComponentsTaxComponentIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTaxCompoent(taxComponentId: number, putTaxesComponentsTaxComponentIdRequest: PutTaxesComponentsTaxComponentIdRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutTaxesComponentsTaxComponentIdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTaxCompoent(taxComponentId, putTaxesComponentsTaxComponentIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TaxComponentsApi - factory interface
 * @export
 */
export const TaxComponentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaxComponentsApiFp(configuration)
    return {
        /**
         * Creates a new Tax Component  Mandatory Fields: name, percentage  Optional Fields: debitAccountType, debitAcountId, creditAccountType, creditAcountId, startDate
         * @summary Create a new Tax Component
         * @param {PostTaxesComponentsRequest} postTaxesComponentsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaxCompoent(postTaxesComponentsRequest: PostTaxesComponentsRequest, options?: any): AxiosPromise<PostTaxesComponentsResponse> {
            return localVarFp.createTaxCompoent(postTaxesComponentsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List Tax Components
         * @summary List Tax Components
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAllTaxComponents(options?: any): AxiosPromise<Array<GetTaxesComponentsResponse>> {
            return localVarFp.retrieveAllTaxComponents(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve Tax Component
         * @summary Retrieve Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTaxComponent(taxComponentId: number, options?: any): AxiosPromise<GetTaxesComponentsResponse> {
            return localVarFp.retrieveTaxComponent(taxComponentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTemplate20(options?: any): AxiosPromise<string> {
            return localVarFp.retrieveTemplate20(options).then((request) => request(axios, basePath));
        },
        /**
         * Updates Tax component. Debit and credit account details cannot be modified. All the future tax components would be replaced with the new percentage.
         * @summary Update Tax Component
         * @param {number} taxComponentId taxComponentId
         * @param {PutTaxesComponentsTaxComponentIdRequest} putTaxesComponentsTaxComponentIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaxCompoent(taxComponentId: number, putTaxesComponentsTaxComponentIdRequest: PutTaxesComponentsTaxComponentIdRequest, options?: any): AxiosPromise<PutTaxesComponentsTaxComponentIdResponse> {
            return localVarFp.updateTaxCompoent(taxComponentId, putTaxesComponentsTaxComponentIdRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaxComponentsApi - object-oriented interface
 * @export
 * @class TaxComponentsApi
 * @extends {BaseAPI}
 */
export class TaxComponentsApi extends BaseAPI {
    /**
     * Creates a new Tax Component  Mandatory Fields: name, percentage  Optional Fields: debitAccountType, debitAcountId, creditAccountType, creditAcountId, startDate
     * @summary Create a new Tax Component
     * @param {PostTaxesComponentsRequest} postTaxesComponentsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxComponentsApi
     */
    public createTaxCompoent(postTaxesComponentsRequest: PostTaxesComponentsRequest, options?: any) {
        return TaxComponentsApiFp(this.configuration).createTaxCompoent(postTaxesComponentsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List Tax Components
     * @summary List Tax Components
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxComponentsApi
     */
    public retrieveAllTaxComponents(options?: any) {
        return TaxComponentsApiFp(this.configuration).retrieveAllTaxComponents(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve Tax Component
     * @summary Retrieve Tax Component
     * @param {number} taxComponentId taxComponentId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxComponentsApi
     */
    public retrieveTaxComponent(taxComponentId: number, options?: any) {
        return TaxComponentsApiFp(this.configuration).retrieveTaxComponent(taxComponentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxComponentsApi
     */
    public retrieveTemplate20(options?: any) {
        return TaxComponentsApiFp(this.configuration).retrieveTemplate20(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates Tax component. Debit and credit account details cannot be modified. All the future tax components would be replaced with the new percentage.
     * @summary Update Tax Component
     * @param {number} taxComponentId taxComponentId
     * @param {PutTaxesComponentsTaxComponentIdRequest} putTaxesComponentsTaxComponentIdRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxComponentsApi
     */
    public updateTaxCompoent(taxComponentId: number, putTaxesComponentsTaxComponentIdRequest: PutTaxesComponentsTaxComponentIdRequest, options?: any) {
        return TaxComponentsApiFp(this.configuration).updateTaxCompoent(taxComponentId, putTaxesComponentsTaxComponentIdRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
