/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetTaxesGroupResponse } from '../models';
// @ts-ignore
import { PostTaxesGroupRequest } from '../models';
// @ts-ignore
import { PostTaxesGroupResponse } from '../models';
// @ts-ignore
import { PutTaxesGroupTaxGroupIdRequest } from '../models';
// @ts-ignore
import { PutTaxesGroupTaxGroupIdResponse } from '../models';
/**
 * TaxGroupApi - axios parameter creator
 * @export
 */
export const TaxGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new Tax Group Mandatory Fields: name and taxComponents Mandatory Fields in taxComponents: taxComponentId Optional Fields in taxComponents: id, startDate and endDate
         * @summary Create a new Tax Group
         * @param {PostTaxesGroupRequest} postTaxesGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaxGroup: async (postTaxesGroupRequest: PostTaxesGroupRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'postTaxesGroupRequest' is not null or undefined
            assertParamExists('createTaxGroup', 'postTaxesGroupRequest', postTaxesGroupRequest)
            const localVarPath = `/taxes/group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postTaxesGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List Tax Group
         * @summary List Tax Group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAllTaxGroups: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxes/group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve Tax Group
         * @summary Retrieve Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTaxGroup: async (taxGroupId: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'taxGroupId' is not null or undefined
            assertParamExists('retrieveTaxGroup', 'taxGroupId', taxGroupId)
            const localVarPath = `/taxes/group/{taxGroupId}`
                .replace(`{${"taxGroupId"}}`, encodeURIComponent(String(taxGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTemplate21: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/taxes/group/template`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates Tax Group. Only end date can be up-datable and can insert new tax components.
         * @summary Update Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {PutTaxesGroupTaxGroupIdRequest} putTaxesGroupTaxGroupIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaxGroup: async (taxGroupId: number, putTaxesGroupTaxGroupIdRequest: PutTaxesGroupTaxGroupIdRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'taxGroupId' is not null or undefined
            assertParamExists('updateTaxGroup', 'taxGroupId', taxGroupId)
            // verify required parameter 'putTaxesGroupTaxGroupIdRequest' is not null or undefined
            assertParamExists('updateTaxGroup', 'putTaxesGroupTaxGroupIdRequest', putTaxesGroupTaxGroupIdRequest)
            const localVarPath = `/taxes/group/{taxGroupId}`
                .replace(`{${"taxGroupId"}}`, encodeURIComponent(String(taxGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication tenantid required
            await setApiKeyToObject(localVarHeaderParameter, "fineract-platform-tenantid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putTaxesGroupTaxGroupIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaxGroupApi - functional programming interface
 * @export
 */
export const TaxGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaxGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new Tax Group Mandatory Fields: name and taxComponents Mandatory Fields in taxComponents: taxComponentId Optional Fields in taxComponents: id, startDate and endDate
         * @summary Create a new Tax Group
         * @param {PostTaxesGroupRequest} postTaxesGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTaxGroup(postTaxesGroupRequest: PostTaxesGroupRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostTaxesGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTaxGroup(postTaxesGroupRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List Tax Group
         * @summary List Tax Group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveAllTaxGroups(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetTaxesGroupResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveAllTaxGroups(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieve Tax Group
         * @summary Retrieve Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveTaxGroup(taxGroupId: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTaxesGroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveTaxGroup(taxGroupId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async retrieveTemplate21(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.retrieveTemplate21(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates Tax Group. Only end date can be up-datable and can insert new tax components.
         * @summary Update Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {PutTaxesGroupTaxGroupIdRequest} putTaxesGroupTaxGroupIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTaxGroup(taxGroupId: number, putTaxesGroupTaxGroupIdRequest: PutTaxesGroupTaxGroupIdRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutTaxesGroupTaxGroupIdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTaxGroup(taxGroupId, putTaxesGroupTaxGroupIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TaxGroupApi - factory interface
 * @export
 */
export const TaxGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaxGroupApiFp(configuration)
    return {
        /**
         * Create a new Tax Group Mandatory Fields: name and taxComponents Mandatory Fields in taxComponents: taxComponentId Optional Fields in taxComponents: id, startDate and endDate
         * @summary Create a new Tax Group
         * @param {PostTaxesGroupRequest} postTaxesGroupRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTaxGroup(postTaxesGroupRequest: PostTaxesGroupRequest, options?: any): AxiosPromise<PostTaxesGroupResponse> {
            return localVarFp.createTaxGroup(postTaxesGroupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List Tax Group
         * @summary List Tax Group
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveAllTaxGroups(options?: any): AxiosPromise<Array<GetTaxesGroupResponse>> {
            return localVarFp.retrieveAllTaxGroups(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve Tax Group
         * @summary Retrieve Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTaxGroup(taxGroupId: number, options?: any): AxiosPromise<GetTaxesGroupResponse> {
            return localVarFp.retrieveTaxGroup(taxGroupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        retrieveTemplate21(options?: any): AxiosPromise<string> {
            return localVarFp.retrieveTemplate21(options).then((request) => request(axios, basePath));
        },
        /**
         * Updates Tax Group. Only end date can be up-datable and can insert new tax components.
         * @summary Update Tax Group
         * @param {number} taxGroupId taxGroupId
         * @param {PutTaxesGroupTaxGroupIdRequest} putTaxesGroupTaxGroupIdRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTaxGroup(taxGroupId: number, putTaxesGroupTaxGroupIdRequest: PutTaxesGroupTaxGroupIdRequest, options?: any): AxiosPromise<PutTaxesGroupTaxGroupIdResponse> {
            return localVarFp.updateTaxGroup(taxGroupId, putTaxesGroupTaxGroupIdRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaxGroupApi - object-oriented interface
 * @export
 * @class TaxGroupApi
 * @extends {BaseAPI}
 */
export class TaxGroupApi extends BaseAPI {
    /**
     * Create a new Tax Group Mandatory Fields: name and taxComponents Mandatory Fields in taxComponents: taxComponentId Optional Fields in taxComponents: id, startDate and endDate
     * @summary Create a new Tax Group
     * @param {PostTaxesGroupRequest} postTaxesGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxGroupApi
     */
    public createTaxGroup(postTaxesGroupRequest: PostTaxesGroupRequest, options?: any) {
        return TaxGroupApiFp(this.configuration).createTaxGroup(postTaxesGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List Tax Group
     * @summary List Tax Group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxGroupApi
     */
    public retrieveAllTaxGroups(options?: any) {
        return TaxGroupApiFp(this.configuration).retrieveAllTaxGroups(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve Tax Group
     * @summary Retrieve Tax Group
     * @param {number} taxGroupId taxGroupId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxGroupApi
     */
    public retrieveTaxGroup(taxGroupId: number, options?: any) {
        return TaxGroupApiFp(this.configuration).retrieveTaxGroup(taxGroupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxGroupApi
     */
    public retrieveTemplate21(options?: any) {
        return TaxGroupApiFp(this.configuration).retrieveTemplate21(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates Tax Group. Only end date can be up-datable and can insert new tax components.
     * @summary Update Tax Group
     * @param {number} taxGroupId taxGroupId
     * @param {PutTaxesGroupTaxGroupIdRequest} putTaxesGroupTaxGroupIdRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxGroupApi
     */
    public updateTaxGroup(taxGroupId: number, putTaxesGroupTaxGroupIdRequest: PutTaxesGroupTaxGroupIdRequest, options?: any) {
        return TaxGroupApiFp(this.configuration).updateTaxGroup(taxGroupId, putTaxesGroupTaxGroupIdRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
