/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetAccountTransfersFromAccountType } from './get-account-transfers-from-account-type';
import { GetAccountTransfersFromClientOptions } from './get-account-transfers-from-client-options';
import { GetAccountTransfersPageItemsCurrency } from './get-account-transfers-page-items-currency';
import { GetAccountTransfersPageItemsFromAccount } from './get-account-transfers-page-items-from-account';
import { GetAccountTransfersPageItemsFromOffice } from './get-account-transfers-page-items-from-office';
import { GetAccountTransfersPageItemsToAccountType } from './get-account-transfers-page-items-to-account-type';

/**
 * 
 * @export
 * @interface GetAccountTransfersPageItems
 */
export interface GetAccountTransfersPageItems {
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransfersPageItems
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetAccountTransfersPageItems
     */
    reversed?: boolean;
    /**
     * 
     * @type {GetAccountTransfersPageItemsCurrency}
     * @memberof GetAccountTransfersPageItems
     */
    currency?: GetAccountTransfersPageItemsCurrency;
    /**
     * 
     * @type {number}
     * @memberof GetAccountTransfersPageItems
     */
    transferAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransfersPageItems
     */
    transferDate?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountTransfersPageItems
     */
    transferDescription?: string;
    /**
     * 
     * @type {GetAccountTransfersPageItemsFromOffice}
     * @memberof GetAccountTransfersPageItems
     */
    fromOffice?: GetAccountTransfersPageItemsFromOffice;
    /**
     * 
     * @type {GetAccountTransfersFromClientOptions}
     * @memberof GetAccountTransfersPageItems
     */
    fromClient?: GetAccountTransfersFromClientOptions;
    /**
     * 
     * @type {GetAccountTransfersFromAccountType}
     * @memberof GetAccountTransfersPageItems
     */
    fromAccountType?: GetAccountTransfersFromAccountType;
    /**
     * 
     * @type {GetAccountTransfersPageItemsFromAccount}
     * @memberof GetAccountTransfersPageItems
     */
    fromAccount?: GetAccountTransfersPageItemsFromAccount;
    /**
     * 
     * @type {GetAccountTransfersPageItemsFromOffice}
     * @memberof GetAccountTransfersPageItems
     */
    toOffice?: GetAccountTransfersPageItemsFromOffice;
    /**
     * 
     * @type {GetAccountTransfersFromClientOptions}
     * @memberof GetAccountTransfersPageItems
     */
    toClient?: GetAccountTransfersFromClientOptions;
    /**
     * 
     * @type {GetAccountTransfersPageItemsToAccountType}
     * @memberof GetAccountTransfersPageItems
     */
    toAccountType?: GetAccountTransfersPageItemsToAccountType;
    /**
     * 
     * @type {GetAccountTransfersPageItemsFromAccount}
     * @memberof GetAccountTransfersPageItems
     */
    toAccount?: GetAccountTransfersPageItemsFromAccount;
}

