/* tslint:disable */
/* eslint-disable */
/**
 * Apache Fineract
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * The version of the OpenAPI document: 1.5.0-66-gffae7d4-dirty
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetChargesChargeCalculationType } from './get-charges-charge-calculation-type';
import { GetChargesChargeTimeType } from './get-charges-charge-time-type';
import { GetChargesCurrencyResponse } from './get-charges-currency-response';

/**
 * GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
 * @export
 * @interface GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
 */
export interface GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse {
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    chargeId?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    name?: string;
    /**
     * 
     * @type {GetChargesChargeTimeType}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    chargeTimeType?: GetChargesChargeTimeType;
    /**
     * 
     * @type {GetChargesChargeCalculationType}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    chargeCalculationType?: GetChargesChargeCalculationType;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    percentage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountPercentageAppliedTo?: number;
    /**
     * 
     * @type {GetChargesCurrencyResponse}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    currency?: GetChargesCurrencyResponse;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountWaived?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountWrittenOff?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountOutstanding?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    amountOrPercentage?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetSavingsAccountsSavingsAccountIdChargesSavingsAccountChargeIdResponse
     */
    penalty?: boolean;
}


